export default {
	FILTER_BAR: {
		INNER_FILTERS: 'FILTER_BAR_INNER_FILTERS',
		TOGGLE: 'FILTER_BAR_TOGGLE',
		TOGGLE_PARENT: 'FILTER_BAR_TOGGLE_PARENT',
		RESET: 'FILTER_RESET',
		NUMBER_OF_ROWS: 'NUMBER_OF_ROWS'
	},
	MULTIPLE_CHOICE_FILTER: {
		BUTTON: 'MULTIPLE_CHOICE_FILTER_BUTTON',
		OPTION: 'MULTIPLE_CHOICE_FILTER_OPTION',
		COMPOSED_OBJECTS_RESULTS_LIST: 'MULTIPLE_CHOICE_FILTER_COMPOSED_OBJECTS_RESULTS_LIST'
	},
	TABLE_ROW: 'TABLE_ROW',
	LEHRENDENEINTRAGUNG: {
		TABELLE: {
			TABLE: 'TABLE',
			RAUM_TREFFPUNKT_SPALTE: {
				CAMPUS: 'LEHRENDENEINTRAGUNG_TABELLE_RAUM_TREFFPUNKT_SPALTE_CAMPUS',
				RAUM: 'LEHRENDENEINTRAGUNG_TABELLE_RAUM_TREFFPUNKT_SPALTE_RAUM',
				TREFFPUNKT: 'LEHRENDENEINTRAGUNG_TABELLE_RAUM_TREFFPUNKT_SPALTE_TREFFPUNKT'
			},
			LEHRTAETIGKEITEN_SPALTE: {
				LEHRENDES: 'LEHRENDENEINTRAGUNG_TABELLE_LEHRTAETIGKEITEN_SPALTE_LEHRENDES',
				EINRICHTUNG: 'LEHRENDENEINTRAGUNG_TABELLE_LEHRTAETIGKEITEN_SPALTE_EINRICHTUNG'
			}
		},
		MULTI_PASTE_INSERT_BUTTON: 'MULTI_PASTE_INSERT_BUTTON',
		MULTI_PASTE_SAVE_BUTTON: 'MULTI_PASTE_SAVE_BUTTON',
		LEHRENDE_NAME_ANZEIGE: 'LEHRENDE_NAME_ANZEIGE',
		INPUT_LEHRENDEN_SELECTION: 'INPUT_LEHRENDEN_SELECTION',
		BUTTON_SAVE_TERMINBEARBEITUNG: 'BUTTON_SAVE_TERMINBEARBEITUNG',
		BUTTON_SAVE_AND_NEXT_TERMINBEARBEITUNG: 'BUTTON_SAVE_AND_NEXT_TERMINBEARBEITUNG',
		ADD_LEHRTAETIGKEIT: 'ADD_LEHRTAETIGKEIT',
		DELETE_LEHRTAETIGKEIT: 'DELETE_LEHRTAETIGKEIT',
		SELECT_EINRICHTUNG: 'SELECT_EINRICHTUNG',
		CLOSE_EDIT_MODE: 'CLOSE_EDIT_MODE',
		INPUT_START_DATE: 'INPUT_START_DATE',
		INPUT_END_DATE: 'INPUT_END_DATE',
		VERTRETUNGSINDICATOR: 'VERTRETUNGSINDICATOR'
	},
	CHIP: 'CHIP',
	ROW_EDIT: 'ROW_EDIT',
	EDIT_BUTTON: 'EDIT_BUTTON',
	DELETE_BUTTON: 'DELETE_BUTTON',
	DRAWER: {
		ID: 'DRAWER',
		LEHRTAETIGKEIT: 'DRAWER_LEHRTAETIGKEIT',
		TERMIN_INFO: 'TERMIN_INFO',
		CLOSE: 'CLOSE_DRAWER'
	},
	CHOSEN_SELECTION: 'CHOSEN_SELECTION',
	SELECT: 'SELECT',
	SELECT_ITEM: 'SELECT_ITEM',
	DROPDOWN: {
		TRIGGER: 'DROPDOWN_TRIGGER',
		MENU: 'DROPDOWN_MENU'
	},
	AUTOCOMPLETE: {
		INPUT: 'AUTOCOMPLETE_INPUT',
		ITEM: 'AUTOCOMPLETE_ITEM',
		RESET: 'AUTOCOMPLETE_RESET',
		ALERT_LABEL: 'AUTOCOMPLETE_ALERT_LABEL'
	},
	CHECKBOX: 'CHECKBOX',

	NAVIGATION_TOOLTIP_TRIGGERER: 'NAVIGATION_TOOLTIP_TRIGGERER',
	TOOLTIP_TRIGGERER: 'TOOLTIP_TRIGGERER',

	SHOWCASE: {
		MULTIPLE_CHOICE_FILTER: {
			SIMPLE_OBJECTS: 'SIMPLE_OBJECTS',
			COMPLEX_OBJECTS: 'COMPLEX_OBJECTS',
			EMPTY_LIST: 'EMPTY_LIST'
		},
		EDITABLE_TABLE: {
			INPUT: 'INPUT'
		},
		AUTOCOMPLETE: {
			PAGE: 'AUTOCOMPLETE_PAGE',
			RESULT: 'AUTOCOMPLETE_RESULT',
			CONFLICT_ICON: {
				ERROR_CALENDER: 'ERROR_CALENDER',
				ERROR_ALERT: 'ERROR_ALERT',
				WARNING_ALERT: 'WARNING_ALERT'
			}
		},
		DROPDOWN: {
			DISABLED: 'DISABLED',
			SIMPLE_OBJECTS: 'SIMPLE_OBJECTS',
			SIMPLE_OBJECTS_AUTOCLOSING: 'SIMPLE_OBJECTS_AUTOCLOSING',
			COMPLEX_OBJECTS: 'COMPLEX_OBJECTS',
			COMPLEX_OBJECTS_AUTOCLOSING: 'COMPLEX_OBJECTS_AUTOCLOSING',
			COMPLEX_OBJECTS_AUTOCLOSING_RESULTS: 'COMPLEX_OBJECTS_AUTOCLOSING_RESULTS',
			SIMPLE_OBJECTS_AUTOCLOSING_CLICK_TARGET: 'SIMPLE_OBJECTS_AUTOCLOSING_CLICK_TARGET',
			COMPLEX_OBJECTS_AUTOCLOSING_CLICK_TARGET: 'COMPLEX_OBJECTS_AUTOCLOSING_CLICK_TARGET'
		},
		WARNING_SIGN: 'SHOWCASE_WARNING_SIGN'
	},
	TREFFPUNKT: {
		ADD: 'ADD_TREFFPUNKT_BUTTON',
		DELETE: 'DELETE_TREFFPUNKT_BUTTON',
		CLEAR: 'CLEAR_TREFFPUNKT_BUTTON',
		INPUT: 'INPUT_TREFFPUNKT'
	},
	ALERT: {
		CLOSE: 'CLOSE',
		ACTION: 'ACTION'
	},
	IS_VERTRETUNG_TOGGLE: 'ISVERTRETUNGTOGGLE',
	BADGE: 'BADGE',
	BREADCRUMBS: 'BREADCRUMBS',
	COLLAPSE_BUTTON: 'COLLAPSE-BUTTON',
	SIDEBAR: 'SIDEBAR',
	CHECKBOX_VALUE: 'CHECKBOX-VALUE',
	WARNING_SIGN: 'WARNING_SIGN'
}
